### PR TITLE
Editing the Patient class and cretting Gender ENUM and some changes

### PR DESCRIPTION
**Pull request by chandant9**
please check if this is okay to be merged

### CODE REVIEW

**Review by Mohrezakhorasany — COMMENTED** [review]
Hey Chandan,

I wouldn't usually give seters out, I do defensive as possible.

We can do it with Setters, but my question is about parameter passing to Patient object, Social security code, so you want me to initialize that first as let's say local variable in the constructor of Patient input management and pass it to Patient object? and why to do that?
and we don't need Arraylist for the patient, anyway, it goes on table in DB and social security will be checked as Unique key, I cant see but did u made any changes on Patient  input management as well 

I like your idea on sex to have enum makes sense

**Comment by chandant9** [comment]
Yes i thought the same about the setters. let me re-review the code.. in PIM i just changed the format from final static to static final, just for convention.
may be you can approve the ones you need and delete the rest and merge

**Comment by Mohrezakhorasany** [comment]
I committed it, by reverting Patient class to the original version and fixing naming convention on regex string literals from PIM

**Comment by chandant9** [comment]
cool thanks

**Pull request merged**
